Bytedoc\Bundle\Gps\Entity\Book:
    type: entity
    table: gps_books
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 128
            unique: true
        category:
            type: string
            length: 64
        author:
            type: string
            length: 128
        href_book:
            type: string
            length: 256
        href_reference:
            type: string
            length: 256
        notes:
            type: text
    manyToOne:
        user:
            targetEntity: User
            inversedBy: books
            joinColumn:
                name: user_id
                referencedColumnName: id
