Bytedoc\GpsBundle\Entity\User:
    type: entity
    table: gps_users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 25
            unique: true
        salt:
            type: string
            length: 32
        password:
            type: string
            length: 88
        email:
            type: string
            length: 128
            unique: true
        isActive:
            type: boolean
