Bytedoc\Bundle\Gps\Entity\Webressource:
    type: entity
    table: gps_webressources
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        category:
            type: string
            length: 50
        title:
            type: string
            length: 128
        href:
            type: string
            length: 256
        rating:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            #inversedBy: webressources
            joinColumn:
                name: user_id
                referencedColumnName: id
