# prefix /gps/
main:
    pattern:  /main/{name}
    defaults: { _controller: BytedocGpsBundle:Main:index, name:nic }

login:
    pattern:  /login
    defaults: { _controller: BytedocGpsBundle:Security:login }

logincheck:
    pattern:  /logincheck

logout:
    pattern:  /logout

read:
    pattern:  /read/{entity}
    defaults: { _controller: BytedocGpsBundle:Read:read, entity:test }

write:
    pattern:  /write/{entity}
    defaults: { _controller: BytedocGpsBundle:Write:write, entity:test }