main:
    pattern:  /main/{name}
    defaults: { _controller: BytedocGpsBundle:Main:index, name:nic }

read:
    pattern:  /read/{entity}
    defaults: { _controller: BytedocGpsBundle:Read:read, entity:test }