parameters:
#    bytedoc_gps.example.class: Bytedoc\Bundle\Gps\Example

services:
#    bytedoc_gps.example:
#        class: %bytedoc_gps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
